import { Request, Response } from 'express'
import * as jwt from 'jsonwebtoken'
import { getManager } from 'typeorm'
import { User } from '../entity/User'
import { logError } from '../service/logger'
